### PR TITLE
fix: resolve widget production rendering failures

### LINKED ISSUE #20: Widgets fail to render in production
## Summary

Widgets do not render in production. The browser console shows:

Uncaught ReferenceError: DEFINES is not defined as well as localhost is reference in widget bundles. The initial version of this template was to get it working with a dev environment and the production path was not complete.

1. HMR client bundled into production JS
The virtual module loader includes `/@vite/client` and `@react-refresh`
unconditionally. These are dev-only Vite internals that reference
`__DEFINES__`, a placeholder that is never substituted in production
builds.

2. Static server SPA mode redirecting widget HTML
The `serve` script uses `-s` (single-page app mode), which redirects
`/echo.html` → `/echo`. With no `index.html` fallback in `assets/`, the
request 404s and the MCP server can never retrieve the widget HTML.

3. BASE_URL baked incorrectly into built HTML
`envDir: '..'` in `vite.config.ts` only populates `import.meta.env` —
not `process.env`. The build plugin falls back to `http://localhost:4444`
and bakes that into the generated HTML asset URLs instead of the
configured `BASE_URL`.

### PR DESCRIPTION
**Pull request by nickytonline**
## Summary                                                                         
                                         
- Gate HMR imports (`/@vite/client`, `@react-refresh`) behind a dev-only check in  
the virtual module loader so they are never bundled into production builds         
- Remove `-s` (SPA mode) from the `serve` script to prevent clean URL rewrites from
 redirecting `/echo.html` to a 404                                                 
- Use `loadEnv` in `vite.config.ts` to explicitly inject `.env` variables into
`process.env` so the widget build plugin picks up `BASE_URL` correctly at build
time
- Add `start`, `start:server`, and `start:widgets` scripts for running the compiled
 server and pre-built widget assets together as a production-like environment

## Test plan

- [x] Run `npm run build:widgets` and confirm `echo.html` references `BASE_URL`
asset URLs (not `localhost:4444`)
- [x] Confirm built JS contains no `__DEFINES__` references
- [x] Run `npm run start` and verify the widget renders correctly end-to-end
- [x] Run `npm run dev` and confirm development mode still works as expected

Fixes #20

### CODE REVIEW

File: server/src/server.ts [hunk 1]
```diff
@@ -102,6 +103,18 @@ async function readWidgetHtml(widgetId: string): Promise<string> {
     }
   }
 
+  if (BASE_URL) {
+    const url = `${BASE_URL}/${widgetId}.html`;
+    logger.debug({ url }, 'Fetching widget HTML from BASE_URL');
```
Comment (nickytonline) [inline server/src/server.ts]: fail fast if no `BASE_URL` for prod.

**Review by wasaga — APPROVED** [review]
